filme_app/urls.py
from django.urls import path
from .views import Homefilmes, DetalhesFilme, PesquisarFilme

app_name = 'filme_app'

urlpatterns = [
    #  filme/
    path('homefilmes/', Homefilmes.as_view(), name='homefilmes'),
    path('detalhes_filme/<int:pk>/',
         DetalhesFilme.as_view(), name='detalhes_filme'),
    path('pesquisarfilme/', PesquisarFilme.as_view(), name='pesquisarfilme')
]

movie_app/urls.py
from django.urls import path, reverse_lazy
from .views import Homepage, CriarConta, EditarPerfil
from django.contrib.auth import views as auth_views
from .import views as logoutview

app_name = 'movie_app'

urlpatterns = [
    path('', Homepage.as_view(), name='homepage'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', logoutview.logout, name='logout'),
    path('criarconta/', CriarConta.as_view(), name='criarconta'),
    path('editarperfil/<int:pk>/',
         EditarPerfil.as_view(), name='editarperfil'),
    path('mudarsenha/', auth_views.PasswordChangeView.as_view(template_name='editarperfil.html',
         success_url=reverse_lazy('filme_app.homefilmes')), name='mudarsenha'),
]

movie_pro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie_app.urls', namespace='movie_app')),
    path('filmes/', include('filme_app.urls', namespace='filme_app')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

filme_app/models.py
from django.db import models


LISTA_CATEGORIAS = (
    ('ANALISES', 'Analises'),
    ('PROGRAMACAO', 'Programacao'),
    ('APRESENTACAO', 'Apresentacao'),
    ('OUTROS', 'Outros'),
)


class Filme(models.Model):
    titulo = models.CharField(max_length=150, unique=True)
    thumb = models.ImageField(upload_to='thumbs_filmes')
    descricao = models.TextField(max_length=1000, blank=True, null=True)
    categoria = models.CharField(
        max_length=32, choices=LISTA_CATEGORIAS, blank=True, null=True)
    visualizacoes = models.IntegerField(default=0)
    data_criacao = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.titulo


class Episodios(models.Model):
    filme = models.ForeignKey(
        Filme, on_delete=models.CASCADE, related_name='epsodios', blank=True, default='')
    nome = models.CharField(
        max_length=150, unique=True, blank=True, null=True)
    link = models.URLField(blank=True, null=True)

    def __str__(self) -> str:
        return self.nome

movie_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
from filme_app.models import Filme


class User(AbstractUser, UserManager):
    username = models.CharField(max_length=150, unique=True)
    email = models.EmailField(max_length=264)
    password = models.CharField(max_length=264)
    filmes_vistos = models.ManyToManyField(
        Filme, related_name='filmes', blank=True)

    def __str__(self):
        return self.username

movie_app/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User
from django import forms


class HomepageForm(forms.Form):
    email = forms.EmailField(label=False)


class CriarContaForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


# class EditarPerfil(UserCreationForm):
#     username = forms.CharField()
#     email = forms.EmailField()

#     class Meta:
#         model = User
#         fields = ('username', 'email')

filme_app/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from .models import Filme
from django.views.generic import DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin


class Homefilmes(LoginRequiredMixin, ListView):
    # O objetivo desta classe é exibir uma lista de objetos.
    template_name = 'homefilmes.html'
    model = Filme
    # ela vai me passar um contexto em forma de object_list


class DetalhesFilme(LoginRequiredMixin, DetailView):
    template_name = 'detalhes_filme.html'
    model = Filme

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        # preciso descobrir qual filme o usuário está acessando
        filme = self.get_object()
        # preciso somar 1 visualização àquele filme
        filme.visualizacoes += 1
        # agora preciso salvar a alteração no banco de dados
        filme.save()
        usuario = request.user
        usuario.filmes_vistos.add(filme)

        return super().get(request, *args, **kwargs)
        # aqui ele redireciona o usuário para a url final

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super(DetalhesFilme, self).get_context_data(**kwargs)
        filmes_relacionados = Filme.objects.filter(
            categoria=self.get_object().categoria)[0:5]
        # no HTML o filme é chamado de object e aqui na views é chamado de get_object. Então, get_objet().categoria

        context["filmes_relacionados"] = filmes_relacionados
        return context

    # Esta classe ao contrário da listview ela me passa somente um object. Funciona como na função get_object.


class PesquisarFilme(LoginRequiredMixin, ListView):
    template_name = 'pesquisarfilme.html'
    model = Filme

    def get_queryset(self) -> QuerySet[Any]:
        termo_pesquisa = self.request.GET.get("query")
        if termo_pesquisa:
            object_list = self.model.objects.filter(
                titulo__icontains=termo_pesquisa)
            return object_list
        else:
            return None

movie_app/views.py
from typing import Any
from django.http import HttpRequest
from django.http.response import HttpResponse as HttpResponse
from django.shortcuts import render, redirect, reverse
from django.views.generic import TemplateView, FormView, UpdateView
from django.contrib import auth
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CriarContaForm, HomepageForm
from .models import User


class Homepage(FormView):
    template_name = 'homepage.html'
    form_class = HomepageForm

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        if request.user.is_authenticated:
            return redirect('filme_app:homefilmes')
        else:
            # retorna o usuário para a classe final da view, no caso homepage
            return super().get(request, *args, **kwargs)

    def get_success_url(self) -> str:
        email = self.request.POST.get("email")
        # Verificar se o usuário está cadastro
        usuario = User.objects.filter(email=email)
        if usuario:
            return reverse('movie_app:login')
        else:
            return reverse('movie_app:criarconta')


class CriarConta(FormView):
    template_name = 'criarconta.html'
    # precisei importar o form personalizado que criei e importar o FormView do django
    form_class = CriarContaForm

    def form_valid(self, form: Any) -> HttpResponse:
        form.save()
        return super().form_valid(form)

    def get_success_url(self) -> str:
        # esta função ESPERA UM LINK como resposta e NÃO uma função de redirecionamento, como por exemplo o redirect.
        return reverse('movie_app:login')


def logout(request):
    auth.logout(request)
    return redirect('movie_app:login')


class EditarPerfil(LoginRequiredMixin, UpdateView):
    template_name = 'editarperfil.html'
    model = User
    fields = ('username', 'email')

    def get_success_url(self) -> str:
        return reverse('filme_app:homefilmes')

filme_app/templates/detalhes_filme.html
{% extends 'base_home.html' %}
{% load static %}

{% block 'title' %}
Detalhes do Filme
{% endblock %}

{% block 'content' %}
<main class='bg-primary_black min-h-screen w-full'>
    <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex  items-end bg-cover"
        style="background-image: url('{{object.thumb.url}}');">
        <div>
            <h2 class="text-6xl font-semibold text-white my-4">
                <a href="{% url 'filme_app:detalhes_filme' object.pk %}">{{object.titulo}}
            </h2></a>
            <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">

                {{object.descricao|slice:":100"}}...
            </p>
            <div class="flex my-4">
                <a href="{{object.epsodios.first.link}}">
                    <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                        <ion-icon name="play" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium">
                            Play
                        </span>
                    </button>
                </a>
            </div>
        </div>
    </section>
    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative">
            <h2 class="text-gray-200 text-3xl font-medium">
                Descrição
                <br>
                {{object.descricao|slice:":100"}}...
            </h2>
            <div class="flex justify-left  items-center min-w-full  movie_lis">
                <h5 class="text-gray-100 text-lg">
                    Visualizações: {{object.visualizacoes}}
                </h5>
            </div>

            <div style='margin-top:2rem;margin-bottom:2rem;'>
                <h2 class="text-gray-200 text-3xl font-medium">
                    Episódios


                </h2>
                {% for epsodio in object.epsodios.all %}
                <h3 class='text-lg'>
                    <a href="{{epsodio.link}}">
                        <p>Episódio {{forloop.counter}}: {{epsodio}}</p>
                    </a>
                </h3>
                {% endfor %}
            </div>

        </div>
    </section>

    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative">
            <h2 class="text-gray-200 text-2xl font-medium">
                Relacionados
            </h2>
            <div class="flex flex-wrap items-center min-w-full movie_lis">
                {% for filme in filmes_relacionados %}
                <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                    <a href="{% url 'filme_app:detalhes_filme' filme.pk %}">
                        <img src="{{filme.thumb.url}}" class="object-cover w-full h-full " alt="">
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>

</main>
{% endblock %}

filme_app/templates/homefilmes.html
{% extends 'base_home.html' %}
{% load static %}

{% block 'title' %}
Homefilmes
{% endblock %}

{% block 'head' %}
<style>
    $itemGrow: 1.2;
    $duration: 250ms;

    html {
        scroll-behavior: smooth;
    }

    body {
        margin: 0;
        background-color: #000;
    }

    h1 {
        font-family: Arial;
        color: red;
        text-align: center;
    }

    .wrapper {
        display: grid;
        grid-template-columns: repeat(3, 100%);
        overflow: hidden;
        scroll-behavior: smooth;

        section {
            width: 100%;
            position: relative;
            margin: 20px 0;

            .item {
                padding: 0 2px;
                transition: $duration all;

                &:hover {
                    margin: 0 40px;
                    transform: scale(1.2);
                }

            }

            a {
                /* position: absolute; */
                color: #fff;
                text-decoration: none;
                font-size: 6em;
                background: rgb(0, 0, 0);
                text-align: center;
                z-index: 1;

            }

            &>a:first-child {
                position: absolute;
                left: 0;
                background: linear-gradient(-90deg, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 1) 100%);
            }

            &>a:last-child {
                position: absolute;
                right: 0;
                background: linear-gradient(90deg, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 1) 100%);
            }
        }
    }

    /* // Remove the arrow for Mobile */
    @media only screen and (max-width: 600px) {
        a.arrow__btn {
            display: none;
        }
    }
</style>
{% endblock %}

{% block 'content' %}
<main class='bg-primary_black min-h-screen w-full'>

    <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex items-end bg-cover"
        style="background-image: url('{{filme_destaque.thumb.url}}');">
        <div>
            <h2 class="text-6xl font-semibold text-white my-4">
                Título
            </h2>
            <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">Descrição
            </p>
            <p>{{filme_destaque.descricao}}</p>
            <div class="flex my-4">
                <a href="{% url 'filme_app:detalhes_filme' filme_destaque.pk %}">
                    <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                        <ion-icon name="play" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium ">
                            Play
                        </span>
                    </button>
                </a>
                <br>

            </div>
        </div>
    </section>


    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative">
            <h2 class="text-gray-200 text-2xl font-medium">
                Lançamentos
            </h2>
            <div class="wrapper">

                <section id="section1recentes" class="flex flex-nowrap items-center justify-center space-x-8">
                    <a href="#section2recentes" class="arrow__btn text-6xl page">‹</a>
                    {% for filme in lista_filmes_recentes %}
                    {% if forloop.counter < 5 %} <div class="item h-64 w-1/4 m-4">
                        <a href="{% url 'filme_app:detalhes_filme' filme.pk %}">
                            <img src="{{filme.thumb.url}}" class="rounded-md w-full h-full object-cover">
                        </a>
            </div>
            {% endif %}
            {% endfor %}
            <a href="#section2recentes" class="arrow__btn text-6xl">›</a>
    </section>
    {% if lista_filmes_recentes|length > 4 %}
    <section id="section2recentes" class="flex flex-nowrap items-center justify-center">
        <a href="#section1recentes" class="arrow__btn text-6xl">‹</a>
        {% for filme in lista_filmes_recentes %}
        {% if forloop.counter > 4 %}
        <div class="item h-64 w-1/4 m-4">
            <a href="{% url 'filme_app:detalhes_filme' filme.pk %}">
                <img src="{{filme.thumb.url}}" class="rounded-md w-full h-full object-cover">
            </a>
        </div>
        {% endif %}
        {% endfor %}
        <a href="#section1recentes" class="arrow__btn text-6xl">›</a>
    </section>
    {% endif %}
    </div>
    </div>
    </section>

    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative">
            <h2 class="text-gray-200 text-2xl font-medium">
                Filmes em Alta
            </h2>
            <div class="wrapper">

                <section id="section1emalta" class="flex flex-nowrap items-center justify-center space-x-8">
                    <a href="#section2emalta" class="arrow__btn text-6xl page">‹</a>
                    {% for filme in lista_filmes_emalta %}
                    {% if forloop.counter < 5 %} <div class="item h-64 w-1/4 m-4">
                        <a href="{% url 'filme_app:detalhes_filme' filme.pk %}">
                            <img src="{{filme.thumb.url}}" class="rounded-md w-full h-full object-cover">
                        </a>
            </div>
            {% endif %}
            {% endfor %}
            <a href="#section2emalta" class="arrow__btn text-6xl">›</a>
    </section>
    {% if lista_filmes_emalta|length > 4 %}
    <section id="section2emalta" class="flex flex-nowrap items-center justify-center">
        <a href="#section1emalta" class="arrow__btn text-6xl">‹</a>
        {% for filme in lista_filmes_emalta %}
        {% if forloop.counter > 4 %}
        <div class="item h-64 w-1/4 m-4">
            <a href="{% url 'filme_app:detalhes_filme' filme.pk %}">
                <img src="{{filme.thumb.url}}" class="rounded-md w-full h-full object-cover">
            </a>
        </div>
        {% endif %}
        {% endfor %}
        <a href="#section1emalta" class="arrow__btn text-6xl">›</a>
    </section>
    {% endif %}
    </div>
    </div>
    </section>

    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative">
            <h2 class="text-gray-200 text-2xl font-medium">
                Assistir Novamente
            </h2>
            <div class="wrapper">

                <section id="section1filmesvistos" class="flex flex-nowrap items-center justify-center space-x-8">
                    <a href="#section2filmesvistos" class="arrow__btn text-6xl page">‹</a>
                    {% for filme in request.user.filmes_vistos.all %}
                    {% if forloop.counter < 5 %} <div class="item h-64 w-1/4 m-4">
                        <a href="{% url 'filme_app:detalhes_filme' filme.pk %}">
                            <img src="{{filme.thumb.url}}" class="rounded-md w-full h-full object-cover">
                        </a>
            </div>
            {% endif %}
            {% endfor %}
            <a href="#section2filmesvistos" class="arrow__btn text-6xl">›</a>
    </section>
    {% if request.user.filmes_vistos.all|length > 4 %}
    <section id="section2filmesvistos" class="flex flex-nowrap items-center justify-center">
        <a href="#section1filmesvistos" class="arrow__btn text-6xl">‹</a>
        {% for filme in request.user.filmes_vistos.all %}
        {% if forloop.counter > 4 %}
        <div class="item h-64 w-1/4 m-4">
            <a href="{% url 'filme_app:detalhes_filme' filme.pk %}">
                <img src="{{filme.thumb.url}}" class="rounded-md w-full h-full object-cover">
            </a>
        </div>
        {% endif %}
        {% endfor %}
        <a href="#section1filmesvistos" class="arrow__btn text-6xl">›</a>
    </section>
    {% endif %}
    </div>
    </div>
    </section>
</main>
{% endblock %}

filme_app/templates/pesquisarfilme.html
{% extends 'base_home.html' %}

{% block 'title' %}
Pesquisar filme
{% endblock %}

{% block 'content' %}
<main class='bg-primary_black min-h-screen w-full'>
    <section class='bg-primary_black  min-h-screen flex justify-center py-10'>
        <div class="p-8 w-10/12 relative">
            <h2 class="text-gray-200 text-2xl font-medium">
                Resultados da Busca
            </h2>
            <div class="flex flex-wrap items-center min-w-full movie_lis">
                {% for filme in object_list %}
                <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                    <a href="{% url 'filme_app:detalhes_filme' filme.pk %}">
                        <img src="{{filme.thumb.url}}" class="object-cover w-full h-full " alt="">
                    </a>
                </div>
                {% endfor %}
            </div>

        </div>
    </section>
</main>
{% endblock %}

movie_app/templates/criarconta.html
{% extends 'base_home.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block 'title' %}
Criar Conta
{% endblock %}

{% block 'content' %}
<header
    class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"
    style="background-image: url('{% static '/img/background_netflix.jpg' %}');">
    <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
        <h2>Usuario</h2>

        <form method="post" action="{% url 'movie_app:criarconta' %}">{% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4 text-2xl">Por favor informe os seus dados</legend>
                {{form|crispy}}
            </fieldset>
            <button class="bg-red-600 py-1 px-3 text-white text-2xl md:text-lg rounded-md" type="submit">Criar
                Conta</button>
        </form>
        <small><a class="text-2xl" href="{% url 'movie_app:login' %}">Já tenho conta</a></small>
    </div>
</header>

<footer class=" px-5 py-10 ">
    <ul class="flex justify-between items-center">

        <li>&copy; 2024</li>
        <li> Feito com Python (Django)</li>
        <li>Livre Comércio BR</li>
    </ul>
</footer>

{% endblock %}

movie_app/templates/editarperfil.html
{% extends 'base_home.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block 'title' %}
Alterar Dados
{% endblock %}

{% block 'head' %}
<style>
    #id_username,
    #id_email {
        width: 120%;
    }
</style>
{% endblock %}

{% block 'content' %}
<header
    class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"
    style="background-image: url('{% static '/img/background_netflix.jpg' %}');">
    <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
        <h2 class="text-2xl">{{request.user}}</h2>

        <form method="post">
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Editar Meus Dados</legend>
                {{form|crispy}}
            </fieldset>
            <button class="bg-red-600 py-1 px-3 text-white md:text-lg rounded-md" type="submit">Editar
                Perfil</button>
        </form>
        <a class="mt-2" href="{% url 'movie_app:mudarsenha' %}">Mudar a minha senha</a>
    </div>
</header>

<footer class=" px-5 py-10 ">
    <ul class="flex justify-between items-center">

        <li>&copy; 2024</li>
        <li> Feito com Python (Django)</li>
        <li>Livre Comércio BR</li>
    </ul>

    {% endblock %}

movie_app/templates/homepage.html
{% extends 'base_home.html' %}
{% load static %}



{% block 'title' %}
Homepage
{% endblock %}

{% block 'head' %}
<style>
    #id_email {
        width: 120%;
        font-size: 16px;
        padding: 0.7rem;
        color: #000000
    }
</style>
{% endblock %}

{% block 'content' %}

<header
    class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"
    style="background-image: url('{% static '/img/background_netflix.jpg' %}');">

    <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">

        <h1 class="font-semibold text-4xl md:text-5xl w-10/12 md:w-3/4 text-center">
            Filmes e séries da MovieFlix, tudo em um só lugar.
        </h1>
        <h3 class="text-xl md:text-xl py-5">
            Assista onde quiser. Cancele quando quiser.
        </h3>
        <h4 class="text-sm md:text-lg pb-3">
            Quer começar? Coloque seu e-mail abaixo para acessar.
        </h4>

        <div class="w-full flex justify-center">
            <div class="flex justify-center items-center w-11/12 md:w-11/12">
                <form method="POST" class="w-6/12 justify-center">{% csrf_token %}
                    <div class="flex flex-grow items-stretch">
                        {{ form }}
                        <button
                            class="bg-red-600 font-medium md:font-normal flex justify-center items-center py-2 px-3 md:px-0 rounded-br-sm rounded-tr-sm md:text-2xl ml-12"
                            type="submit">
                            <span>
                                Acessar
                            </span>
                            <ion-icon name="chevron-forward-outline" class="text-2xl"></ion-icon>
                        </button>
                    </div>
                </form>

            </div>
        </div>

    </div>
</header>

<section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
    <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10 ">
        <h2 class="md:text-5xl text-4xl font-semibold mb-4">
            Enjoy on your TV.
        </h2>
        <h5 class="md:text-xl text-lg">
            Watch on Smart TVs, Playstation, Xbox, Chromecast, Apple TV, Blu-ray players, and more.
        </h5>
    </div>
    <div class='md:w-1/2 flex justify-center items-center'>
        <img src="{% static 'img/tv.png' %}" class="w-8/12" alt="">
    </div>
</section>

<section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
    <div class='md:w-1/2 flex justify-center items-center '>
        <img src="{% static 'img/mobile-0819.jpg' %}" class="w-8/12" alt="">
    </div>

    <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
        <h2 class="md:text-5xl text-4xl font-semibold mb-4">
            Download your shows to watch offline.
        </h2>
        <h5 class="md:text-xl text-lg">
            Save your favorites easily and always have something to watch.
        </h5>
    </div>

</section>

<section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
    <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
        <h2 class="md:text-5xl text-4xl font-semibold mb-4">
            Create profiles for kids.
        </h2>
        <h5 class="md:text-xl text-lg">
            Send kids on adventures with their favorite characters in a space made just for them—free with your
            membership.
        </h5>
    </div>
    <div class='md:w-1/2 flex justify-center items-center'>
        <img src="{% static 'img/netflix_kid.png' %}" class="w-8/12" alt="">
    </div>
</section>
<footer class=" px-5 py-10 ">
    <ul class="flex justify-between items-center">

        <li>&copy; 2024</li>
        <li> Feito com Python (Django)</li>
        <li>Livre Comércio BR</li>
    </ul>
</footer>


{% endblock %}

movie_app/templates/login_projeto.html
    <header class="min-h-screen bg-black bg-opacity-75 showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('#');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <form method="post">
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Faça Login para continuar</legend>
                </fieldset>
                <button class="bg-primary_red py-1 my-2 px-3 w-full text-white md:text-lg rounded-md" type="submit">Fazer Login</button>
            </form>
            <small>
                Não tem uma conta ainda? <p><a href="#">Clique aqui para criar uma conta</a></p>
            </small>
        </div>
    </header>

    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">
            
            <li>&copy; 2021</li>
            <li> Feito com Python (Django)</li>
            <li>Hashtag</li>
        </ul>
    </footer>

templates/navbar.html
{% load static %}

<nav class="w-full flex justify-between items-center py-3 px-3 fixed z-50">
    <div class="w-6/12">
        <a href="{% url 'movie_app:homepage' %}">
            <img src="{% static 'img/hashflix.png' %}" alt="" class="w-2/12">
        </a>
    </div>

    <div class="w-6/12 flex flex-now-wrapper justify-end">
        {% if request.user.is_authenticated %}
        <div class="mr-2">
            <form action="{% url 'filme_app:pesquisarfilme' %}" method="GET">
                <input type="text" class="py-1 px-2 rounded-md text-black" placeholder="Pesquisar..." name="query"
                    value="{{request.GET.query}}">
                <input type="submit" value="">
            </form>
        </div>
        {% endif %}

        {% if request.user.is_authenticated %}
        <div class="mr-2">
            <a href="{% url 'movie_app:logout' %}">
                <button class="bg-red-600 text-white py-1 px-3 rounded-md">
                    Sair
                </button>
            </a>
            <a href="{% url 'movie_app:editarperfil' request.user.pk %}">
                <button class="bg-red-600 text-white py-1 px-3 rounded-md">
                    Editar Perfil
                </button>
            </a>
        </div>
        {% else %}
        <div class="mr-2">
            <a href="{% url 'movie_app:login' %}">
                <button class="bg-red-600 text-white py-1 px-3 rounded-md">
                    Login
                </button>
            </a>
        </div>
        <div class="mr-2">
            <a href="{% url 'movie_app:criarconta' %}">
                <button class="bg-red-600 text-white py-1 px-3 rounded-md">
                    Criar Conta
                </button>
            </a>
        </div>
        {% endif %}

    </div>
</nav>